version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    command: >
      sh -c "node seedDatabase.js && node index.js"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"